os:
- linux

language: rust
rust:
- stable

cache:
- apt

matrix:
  include:
    - env:
      - TARGET=x86_64-unknown-linux-gnu
    - env:
      - TARGET=x86_64-pc-windows-gnu

before_install:
  - sudo apt-get update
  - sudo apt-get install -y jq 
  - |
    if [[ $TARGET =~ windows ]]; then
      sudo apt-get intall -y zip mingw-w64
    fi
  - |
    if [[ $TARGET =~ linux ]]; then
      sudo apt-get install tar
    fi

install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup target add $TARGET || true
  - |
    if [ $TARGET == x86_64-pc-windows-gnu ]; then
      mkdir -p ~/.cargo
      echo >> ~/.cargo/config			
      echo '[target.x86_64-pc-windows-gnu]' >> ~/.cargo/config
      echo 'linker = "x86_64-w64-mingw32-gcc"' >> ~/.cargo/config
      echo 'ar = "x86_64-w64-mingw32-gcc-ar"' >> ~/.cargo/config
    fi

script:
  - cd src-binary
  - cargo build --target $TARGET --verbose --release

before_deploy:
  - export CARGO_METADATA=$(cargo metadata --no-deps --format-version 1)
  - export APP_NAME=$(echo $CARGO_METADATA | jq -r '.packages[0].name')
  - export APP_VERSION=$(echo $CARGO_METADATA | jq -r '.packages[0].version')
  - |
    if [[ $TARGET =~ 64 ]]; then
      TARGET_PRETTY="x86_64"
    else
      TARGET_PRETTY="i686"
    fi
  - |
    if [[ $TARGET =~ linux ]]; then
      TARGET_PRETTY=nix-$TARGET_PRETTY
    fi
  - |
    if [[ $TARGET =~ windows ]]; then
      TARGET_PRETTY=win-$TARGET_PRETTY
    fi
  - |
    if [ $TARGET =~ "windows" ]; then
      FILES=$(find target/$TARGET/release/$RELEASE* ! -iname '*.d')
      PACKAGE=$APP_NAME-$APP_VERSION-$TARGET_PRETTY.zip
      zip -j releases/$PACKAGE $FILES >/dev/null 2>/dev/null
    fi
  - |
    if [ $TARGET =~ "linux" ]; then
      FILES=$(find target/$TARGET/release/$RELEASE* ! -iname '*.d' | sed "s/[^\/]*\/[^\/]*\/[^\/]*\///")
      PACKAGE=$APP_NAME-$APP_VERSION-$TARGET_PRETTY.tar.xz
      tar cf releases/$PACKAGE -C target/$TARGET/release $FILES >/dev/null 2>/dev/null
    fi

deploy:
  provider: releases
  api_key:
    secure: YOUR SECURITY KEY
  file: ${PACKAGE}
  skip_cleanup: true
  on:
    tags: true
    repo: YOURREPONAME