[package]
name = "lpsettings-bin"
version = "0.2.2"
authors = ["snsvrno <snsvrno@tuta.io>"]

[dependencies]
lpsettings = { path = "../" }
clap = "2.32"
ansi_term = "0.11"
pretty_env_logger = "0.2"
log = "0"
updater-lp = "0.3"

[[bin]]
name = "lpsettings"
path = "main.rs"