[package]
name = "lpsettings-bin"
version = "0.2.3"
authors = ["snsvrno <snsvrno@tuta.io>"]

[dependencies]
clap = "2.32"
ansi_term = "0.11"
lpsettings = { path = "../lpsettings", version = "0.2.3", features = ["cli"] }
pretty_env_logger = "0.2"
log = "0"
updater-lp = "0.3"